# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/AIagents',
                'doc_host': 'https://apingali.github.io',
                'git_url': 'https://github.com/apingali/AIagents',
                'lib_path': 'AIagents'},
  'syms': {'AIagents.core': {'AIagents.core.foo': ('core.html#foo', 'AIagents/core.py')}}}
